port: 7890
socks-port: 7891
redir-port: 7892
allow-lan: false
mode: rule
log-level: silent
external-controller: 0.0.0.0:9090
secret: ""

Proxy:
# shadowsocks
# The supported ciphers(encrypt methods):
#   aes-128-gcm aes-192-gcm aes-256-gcm
#   chacha20-ietf-poly1305 xchacha20-ietf-poly1305
#   aes-128-cfb aes-192-cfb aes-256-cfb
#   aes-128-ctr aes-192-ctr aes-256-ctr
#   rc4-md5 chacha20 chacha20-ietf xchacha20
  - name: 台湾
    type: socks5
    server: 181.215.45.58
    port: "50101"
    username: qazwsxedc9966333
    password: ZFLLg4UVQH
Proxy Group:
  - name: 国外流量
    type: select
    proxies:
      - 台湾
      - DIRECT
Rule:
  - DOMAIN-SUFFIX,smtp,DIRECT
  - DOMAIN-KEYWORD,aria2,DIRECT
  - DOMAIN,images-cn.ssl-images-amazon.com,DIRECT
  - IP-CIDR,119.28.28.28/32,DIRECT,no-resolve
  - GEOIP,CN,DIRECT
  - MATCH,台湾